version: '3'
services:
  nlu:
    image: nlu
    build: ./nlu
    env_file:
      - .env
    ports:
      - '8080:8080'
  bot:
    image: bot
    build: ./bot
    env_file:
      - .env
    ports:
      - '8000:9999'
    depends_on: 
      - nlu
      - menu
  menu: 
    image: menu
    build: ./menu
    env_file:
      - .env
    ports:
      - '3000:3000'
